' Figure 8.2: Use case diagram for the SafeHome system
@startuml
!theme vibrant
left to right direction

actor Homeowner

rectangle SafeHome {
    usecase "Sets alarm" as UC3
    usecase "Configures\nSafeHome\nsystem parameters" as UC2
    usecase "Access camera \nsurveillance via\nthe Internet" as UC1
}

Homeowner -- UC1
Homeowner -- UC2
Homeowner -- UC3

rectangle Cameras
UC1 -- Cameras

@enduml